---
title: "Proteome_Profiling_mRNA_qp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#### required library and files
library(dplyr)
library(ggplot2)
library(cowplot)
library(tidyr)
library(stringr)
library(readr)
library(readxl)

nameDictionary_RNA_Protein <-read_csv("~/Desktop/GitHub/proteome-profiling-ecoli/Files/nameDictionary_RNA_Protein.csv")

metaData_mrna <- read_csv("~/Desktop/GitHub/proteome-profiling-ecoli/umut/metaData_mrna_trT_set00_StcAllEx_SYAN_baseMgAllMg_baseNaAllNa_ExpAllPhase_noFilter_p1Sf_noNorm.csv")

mRNA_untransformed  <- read_csv("~/Desktop/GitHub/proteome-profiling-ecoli/umut/resDf_mrna_trT_set00_StcAllEx_SYAN_baseMgAllMg_baseNaAllNa_ExpAllPhase_noFilter_p1Sf_noNorm.csv")

Quantitative_Proteomics <- read_excel("~/Desktop/Quantitative Proteomics.xlsx")
```

The following code is used to calculate and plot the ribosomal mRNA fraction of samples during exponential phase using untransformed data

```{r}
####*********
#changing column names 
names(nameDictionary_RNA_Protein)[names(nameDictionary_RNA_Protein) == 'b#'] <- 'b'

names(mRNA_untransformed)[names(mRNA_untransformed) == 'X1'] <- 'mRNA_ID'
####*********


####*********
#join untransformed data to nameDictionary by mRNA_ID
mRNA_untransformed %>% 
  left_join(nameDictionary_RNA_Protein, by = 'mRNA_ID') %>% 
  subset(select = -c(Protein_id, b)) %>% 
  select(mRNA_ID, gene_name, everything())-> UTmNames

UTmNames %>% subset(select = (-c(mRNA_ID))) -> UTmNames
####*********


####*********
#change name of gene_name to Gene, and join df to QP

names(UTmNames)[names(UTmNames) == 'gene_name'] <- 'Gene'
UTmNames %>%
  right_join(Quantitative_Proteomics, by = 'Gene') -> amRNA
 amRNA %>% 
  subset(select = -c(Sector:`1.0397`)) -> amRNA

#remove genes for which there is no data available
amRNA %>% na.omit() -> bmRNA
####*********

####*********
#sum gene counts for each media, filter only ribosomal genes, sum ribosomal gene counts for each media, calculate ribosomal fraction 
bmRNA %>% gather(sample, count, MURI_016:MURI_171) %>% 
  group_by(sample) %>% mutate(total= sum(count)) %>%
  filter(str_detect(Gene,regex('^rp'))) %>% 
  group_by(sample) %>% mutate(mRNA = sum(count)) %>% 
  mutate(fraction = mRNA/total)-> UTtotalmRNA

UTtotalmRNA %>% 
  subset(select = -c(Gene,count, total, mRNA )) %>% 
  distinct(fraction) -> UTmfraction 
####*********


####*********
names(metaData_mrna)[names(metaData_mrna) == 'dataSet'] <- 'sample'

#join metadata (includes growth conditions and generation times) and fraction by sample
UTmfraction %>% left_join(metaData_mrna, by = 'sample') %>% 
  select(-fraction,fraction)-> UTmready
####*********


####********
#calculate generations per hour
UTmready %>% mutate(generations_per_hour = ((growthTime_hr*60)/doublingTimeMinutes)/growthTime_hr) -> UTmready
####********


####*********
#average the ribosomal fractions of samples that have the same doubling time
UTmready %>% group_by(doublingTimeMinutes) %>% 
  mutate(fraction_avg = (sum(fraction))/n()) -> UTmready
####*********


####*********
#unique fraction averages
UTmready %>% distinct(fraction_avg, .keep_all = TRUE) -> UTmfinal
###**********


####*********
#plot of fractions
UTmready %>% ggplot(aes(x=generations_per_hour, y=fraction, color=carbonSource)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=sample),hjust='inward', vjust=1 , size= 5)
####*********


####*********
#plot of fraction averages
UTmfinal %>% ggplot(aes(x=generations_per_hour, y=fraction_avg, color=carbonSource)) + xlab('Generations per Hour') + ylab('mRNA Fraction') + geom_point() + geom_text(aes(label=sample),hjust='inward', vjust=1 , size= 5)
####*********


####*********
#get rid of NaCl and MgSO4 stress 
UTmfinal_alt <- UTmfinal[!grepl("stress", UTmfinal$experiment),]
#get rid of NaCl and MgSO4 stress (non-unique fraction_avg)
UTmfinal_alt2 <- UTmready[!grepl("stress", UTmready$experiment),]
####*********

UTmfinal_alt2 %>% ggplot(aes(x=generations_per_hour, y=fraction, color=carbonSource)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=sample),hjust='inward', vjust=1 , size= 5) 

UTmfinal_alt %>% ggplot(aes(x=generations_per_hour, y=fraction_avg, color=carbonSource)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=sample),hjust='inward', vjust=1 , size= 5)

```

Na concentrations and NaCl stress with untransformed data
```{r}

#non-distinct ribosomal fraction NaCl stress
UTmready %>% filter(experiment == 'NaCl_stress') %>% ungroup() -> UTma

UTma %>% ggplot(aes(x=generations_per_hour, y=fraction, color=sample)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=Na_mM),hjust='inward', vjust=1 , size= 5) 

#keep only ond samples on NaCL stress with unique Na concentrations (5,100,200,300)
UTmready %>% filter(experiment == 'NaCl_stress') %>% ungroup() %>% distinct(Na_mM, carbonSource,.keep_all = TRUE) -> UTmNa

UTmNa %>% ggplot(aes(x=generations_per_hour, y=fraction_avg, color=sample)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=Na_mM),hjust='inward', vjust=1 , size= 5) 
```


Mg concentrations and MgSO4 stress
``` {r}
#non-distinct ribosomal fraction MgSO4 stress
UTmready %>% filter(experiment == 'MgSO4_stress_high'| experiment == 'MgSO4_stress_low') %>% ungroup() -> UTmb

UTmb %>% ggplot(aes(x=generations_per_hour, y=fraction,color=Mg_mM_Levels )) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=Mg_mM),hjust='inward', vjust=1 , size= 5) 

#keep only ond samples on MgSO4 stress with unique Mg concentrations 
UTmready %>% filter(experiment == 'MgSO4_stress_high'| experiment == 'MgSO4_stress_low') %>% ungroup() %>% distinct(Mg_mM, carbonSource,.keep_all = TRUE) -> UTmMg

UTmMg %>% ggplot(aes(x=generations_per_hour, y=fraction_avg, color=sample)) + xlab('Generations per Hour') + ylab('Ribosomal Fraction') + geom_point() + geom_text(aes(label=Mg_mM),hjust='inward', vjust=1 , size= 5) 

```

